# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class TransitStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetString = channel.unary_unary(
                '/grpc_test.Transit/GetString',
                request_serializer=test__pb2.emptyparameter.SerializeToString,
                response_deserializer=test__pb2.StringReply.FromString,
                )
        self.GetNum = channel.unary_unary(
                '/grpc_test.Transit/GetNum',
                request_serializer=test__pb2.NumRequest.SerializeToString,
                response_deserializer=test__pb2.NumReply.FromString,
                )
        self.GetList = channel.unary_unary(
                '/grpc_test.Transit/GetList',
                request_serializer=test__pb2.indexquery.SerializeToString,
                response_deserializer=test__pb2.ListReply.FromString,
                )


class TransitServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetString': grpc.unary_unary_rpc_method_handler(
                    servicer.GetString,
                    request_deserializer=test__pb2.emptyparameter.FromString,
                    response_serializer=test__pb2.StringReply.SerializeToString,
            ),
            'GetNum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNum,
                    request_deserializer=test__pb2.NumRequest.FromString,
                    response_serializer=test__pb2.NumReply.SerializeToString,
            ),
            'GetList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetList,
                    request_deserializer=test__pb2.indexquery.FromString,
                    response_serializer=test__pb2.ListReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_test.Transit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transit(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_test.Transit/GetString',
            test__pb2.emptyparameter.SerializeToString,
            test__pb2.StringReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_test.Transit/GetNum',
            test__pb2.NumRequest.SerializeToString,
            test__pb2.NumReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_test.Transit/GetList',
            test__pb2.indexquery.SerializeToString,
            test__pb2.ListReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
