# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='grpc_test',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\x12\tgrpc_test\"#\n\x0e\x65mptyparameter\x12\x11\n\tsomething\x18\x01 \x01(\t\"\x1e\n\x0bStringReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\nNumRequest\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02x2\x18\x02 \x01(\x02\"\x15\n\x08NumReply\x12\t\n\x01y\x18\x01 \x01(\x02\"\x19\n\nindexquery\x12\x0b\n\x03ind\x18\x01 \x01(\x05\"\x1e\n\tListReply\x12\x11\n\tListReply\x18\x01 \x03(\x02\x32\xbd\x01\n\x07Transit\x12@\n\tGetString\x12\x19.grpc_test.emptyparameter\x1a\x16.grpc_test.StringReply\"\x00\x12\x36\n\x06GetNum\x12\x15.grpc_test.NumRequest\x1a\x13.grpc_test.NumReply\"\x00\x12\x38\n\x07GetList\x12\x15.grpc_test.indexquery\x1a\x14.grpc_test.ListReply\"\x00\x62\x06proto3'
)




_EMPTYPARAMETER = _descriptor.Descriptor(
  name='emptyparameter',
  full_name='grpc_test.emptyparameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='something', full_name='grpc_test.emptyparameter.something', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=60,
)


_STRINGREPLY = _descriptor.Descriptor(
  name='StringReply',
  full_name='grpc_test.StringReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc_test.StringReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=92,
)


_NUMREQUEST = _descriptor.Descriptor(
  name='NumRequest',
  full_name='grpc_test.NumRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x1', full_name='grpc_test.NumRequest.x1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x2', full_name='grpc_test.NumRequest.x2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=130,
)


_NUMREPLY = _descriptor.Descriptor(
  name='NumReply',
  full_name='grpc_test.NumReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='y', full_name='grpc_test.NumReply.y', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=153,
)


_INDEXQUERY = _descriptor.Descriptor(
  name='indexquery',
  full_name='grpc_test.indexquery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ind', full_name='grpc_test.indexquery.ind', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=180,
)


_LISTREPLY = _descriptor.Descriptor(
  name='ListReply',
  full_name='grpc_test.ListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ListReply', full_name='grpc_test.ListReply.ListReply', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['emptyparameter'] = _EMPTYPARAMETER
DESCRIPTOR.message_types_by_name['StringReply'] = _STRINGREPLY
DESCRIPTOR.message_types_by_name['NumRequest'] = _NUMREQUEST
DESCRIPTOR.message_types_by_name['NumReply'] = _NUMREPLY
DESCRIPTOR.message_types_by_name['indexquery'] = _INDEXQUERY
DESCRIPTOR.message_types_by_name['ListReply'] = _LISTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

emptyparameter = _reflection.GeneratedProtocolMessageType('emptyparameter', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYPARAMETER,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.emptyparameter)
  })
_sym_db.RegisterMessage(emptyparameter)

StringReply = _reflection.GeneratedProtocolMessageType('StringReply', (_message.Message,), {
  'DESCRIPTOR' : _STRINGREPLY,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.StringReply)
  })
_sym_db.RegisterMessage(StringReply)

NumRequest = _reflection.GeneratedProtocolMessageType('NumRequest', (_message.Message,), {
  'DESCRIPTOR' : _NUMREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.NumRequest)
  })
_sym_db.RegisterMessage(NumRequest)

NumReply = _reflection.GeneratedProtocolMessageType('NumReply', (_message.Message,), {
  'DESCRIPTOR' : _NUMREPLY,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.NumReply)
  })
_sym_db.RegisterMessage(NumReply)

indexquery = _reflection.GeneratedProtocolMessageType('indexquery', (_message.Message,), {
  'DESCRIPTOR' : _INDEXQUERY,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.indexquery)
  })
_sym_db.RegisterMessage(indexquery)

ListReply = _reflection.GeneratedProtocolMessageType('ListReply', (_message.Message,), {
  'DESCRIPTOR' : _LISTREPLY,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.ListReply)
  })
_sym_db.RegisterMessage(ListReply)



_TRANSIT = _descriptor.ServiceDescriptor(
  name='Transit',
  full_name='grpc_test.Transit',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=215,
  serialized_end=404,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetString',
    full_name='grpc_test.Transit.GetString',
    index=0,
    containing_service=None,
    input_type=_EMPTYPARAMETER,
    output_type=_STRINGREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetNum',
    full_name='grpc_test.Transit.GetNum',
    index=1,
    containing_service=None,
    input_type=_NUMREQUEST,
    output_type=_NUMREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetList',
    full_name='grpc_test.Transit.GetList',
    index=2,
    containing_service=None,
    input_type=_INDEXQUERY,
    output_type=_LISTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSIT)

DESCRIPTOR.services_by_name['Transit'] = _TRANSIT

# @@protoc_insertion_point(module_scope)
